//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMWelfare.LoginService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdEntry", Namespace="http://mgt-svr/loginService/")]
    [System.SerializableAttribute()]
    public partial class AdEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string useridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string snField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string physicalDeliveryOfficeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telephoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string givenNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string displayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string proxyAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailNicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string employeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sAMAccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ipPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string middleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userid {
            get {
                return this.useridField;
            }
            set {
                if ((object.ReferenceEquals(this.useridField, value) != true)) {
                    this.useridField = value;
                    this.RaisePropertyChanged("userid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cn {
            get {
                return this.cnField;
            }
            set {
                if ((object.ReferenceEquals(this.cnField, value) != true)) {
                    this.cnField = value;
                    this.RaisePropertyChanged("cn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sn {
            get {
                return this.snField;
            }
            set {
                if ((object.ReferenceEquals(this.snField, value) != true)) {
                    this.snField = value;
                    this.RaisePropertyChanged("sn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string physicalDeliveryOfficeName {
            get {
                return this.physicalDeliveryOfficeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.physicalDeliveryOfficeNameField, value) != true)) {
                    this.physicalDeliveryOfficeNameField = value;
                    this.RaisePropertyChanged("physicalDeliveryOfficeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string telephoneNumber {
            get {
                return this.telephoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.telephoneNumberField, value) != true)) {
                    this.telephoneNumberField = value;
                    this.RaisePropertyChanged("telephoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string givenName {
            get {
                return this.givenNameField;
            }
            set {
                if ((object.ReferenceEquals(this.givenNameField, value) != true)) {
                    this.givenNameField = value;
                    this.RaisePropertyChanged("givenName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.displayNameField, value) != true)) {
                    this.displayNameField = value;
                    this.RaisePropertyChanged("displayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentField, value) != true)) {
                    this.departmentField = value;
                    this.RaisePropertyChanged("department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string company {
            get {
                return this.companyField;
            }
            set {
                if ((object.ReferenceEquals(this.companyField, value) != true)) {
                    this.companyField = value;
                    this.RaisePropertyChanged("company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string proxyAddresses {
            get {
                return this.proxyAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.proxyAddressesField, value) != true)) {
                    this.proxyAddressesField = value;
                    this.RaisePropertyChanged("proxyAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string mailNickname {
            get {
                return this.mailNicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.mailNicknameField, value) != true)) {
                    this.mailNicknameField = value;
                    this.RaisePropertyChanged("mailNickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string employeeID {
            get {
                return this.employeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.employeeIDField, value) != true)) {
                    this.employeeIDField = value;
                    this.RaisePropertyChanged("employeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string sAMAccountName {
            get {
                return this.sAMAccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.sAMAccountNameField, value) != true)) {
                    this.sAMAccountNameField = value;
                    this.RaisePropertyChanged("sAMAccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string ipPhone {
            get {
                return this.ipPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ipPhoneField, value) != true)) {
                    this.ipPhoneField = value;
                    this.RaisePropertyChanged("ipPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileField, value) != true)) {
                    this.mobileField = value;
                    this.RaisePropertyChanged("mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.middleNameField, value) != true)) {
                    this.middleNameField = value;
                    this.RaisePropertyChanged("middleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mgt-svr/loginService/", ConfigurationName="LoginService.UraLoginServiceSoap")]
    public interface UraLoginServiceSoap {
        
        // CODEGEN: Generating message contract since element name accountName from namespace http://mgt-svr/loginService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mgt-svr/loginService/GetUser", ReplyAction="*")]
        PMWelfare.LoginService.GetUserResponse GetUser(PMWelfare.LoginService.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mgt-svr/loginService/GetUser", ReplyAction="*")]
        System.Threading.Tasks.Task<PMWelfare.LoginService.GetUserResponse> GetUserAsync(PMWelfare.LoginService.GetUserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://mgt-svr/loginService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mgt-svr/loginService/AuthenticateUser", ReplyAction="*")]
        PMWelfare.LoginService.AuthenticateUserResponse AuthenticateUser(PMWelfare.LoginService.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mgt-svr/loginService/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<PMWelfare.LoginService.AuthenticateUserResponse> AuthenticateUserAsync(PMWelfare.LoginService.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://mgt-svr/loginService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mgt-svr/loginService/AuthenticateDomainUser", ReplyAction="*")]
        PMWelfare.LoginService.AuthenticateDomainUserResponse AuthenticateDomainUser(PMWelfare.LoginService.AuthenticateDomainUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mgt-svr/loginService/AuthenticateDomainUser", ReplyAction="*")]
        System.Threading.Tasks.Task<PMWelfare.LoginService.AuthenticateDomainUserResponse> AuthenticateDomainUserAsync(PMWelfare.LoginService.AuthenticateDomainUserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://mgt-svr/loginService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mgt-svr/loginService/ChangeDomainPassword", ReplyAction="*")]
        PMWelfare.LoginService.ChangeDomainPasswordResponse ChangeDomainPassword(PMWelfare.LoginService.ChangeDomainPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mgt-svr/loginService/ChangeDomainPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<PMWelfare.LoginService.ChangeDomainPasswordResponse> ChangeDomainPasswordAsync(PMWelfare.LoginService.ChangeDomainPasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUser", Namespace="http://mgt-svr/loginService/", Order=0)]
        public PMWelfare.LoginService.GetUserRequestBody Body;
        
        public GetUserRequest() {
        }
        
        public GetUserRequest(PMWelfare.LoginService.GetUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mgt-svr/loginService/")]
    public partial class GetUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string whoIsSearching;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string herPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string domain;
        
        public GetUserRequestBody() {
        }
        
        public GetUserRequestBody(string accountName, string whoIsSearching, string herPassword, string domain) {
            this.accountName = accountName;
            this.whoIsSearching = whoIsSearching;
            this.herPassword = herPassword;
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserResponse", Namespace="http://mgt-svr/loginService/", Order=0)]
        public PMWelfare.LoginService.GetUserResponseBody Body;
        
        public GetUserResponse() {
        }
        
        public GetUserResponse(PMWelfare.LoginService.GetUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mgt-svr/loginService/")]
    public partial class GetUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PMWelfare.LoginService.AdEntry GetUserResult;
        
        public GetUserResponseBody() {
        }
        
        public GetUserResponseBody(PMWelfare.LoginService.AdEntry GetUserResult) {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUser", Namespace="http://mgt-svr/loginService/", Order=0)]
        public PMWelfare.LoginService.AuthenticateUserRequestBody Body;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(PMWelfare.LoginService.AuthenticateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mgt-svr/loginService/")]
    public partial class AuthenticateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public AuthenticateUserRequestBody() {
        }
        
        public AuthenticateUserRequestBody(string username, string pwd) {
            this.username = username;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserResponse", Namespace="http://mgt-svr/loginService/", Order=0)]
        public PMWelfare.LoginService.AuthenticateUserResponseBody Body;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(PMWelfare.LoginService.AuthenticateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mgt-svr/loginService/")]
    public partial class AuthenticateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateUserResult;
        
        public AuthenticateUserResponseBody() {
        }
        
        public AuthenticateUserResponseBody(string AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateDomainUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateDomainUser", Namespace="http://mgt-svr/loginService/", Order=0)]
        public PMWelfare.LoginService.AuthenticateDomainUserRequestBody Body;
        
        public AuthenticateDomainUserRequest() {
        }
        
        public AuthenticateDomainUserRequest(PMWelfare.LoginService.AuthenticateDomainUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mgt-svr/loginService/")]
    public partial class AuthenticateDomainUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string domain;
        
        public AuthenticateDomainUserRequestBody() {
        }
        
        public AuthenticateDomainUserRequestBody(string username, string pwd, string domain) {
            this.username = username;
            this.pwd = pwd;
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateDomainUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateDomainUserResponse", Namespace="http://mgt-svr/loginService/", Order=0)]
        public PMWelfare.LoginService.AuthenticateDomainUserResponseBody Body;
        
        public AuthenticateDomainUserResponse() {
        }
        
        public AuthenticateDomainUserResponse(PMWelfare.LoginService.AuthenticateDomainUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mgt-svr/loginService/")]
    public partial class AuthenticateDomainUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateDomainUserResult;
        
        public AuthenticateDomainUserResponseBody() {
        }
        
        public AuthenticateDomainUserResponseBody(string AuthenticateDomainUserResult) {
            this.AuthenticateDomainUserResult = AuthenticateDomainUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeDomainPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeDomainPassword", Namespace="http://mgt-svr/loginService/", Order=0)]
        public PMWelfare.LoginService.ChangeDomainPasswordRequestBody Body;
        
        public ChangeDomainPasswordRequest() {
        }
        
        public ChangeDomainPasswordRequest(PMWelfare.LoginService.ChangeDomainPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mgt-svr/loginService/")]
    public partial class ChangeDomainPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string domain;
        
        public ChangeDomainPasswordRequestBody() {
        }
        
        public ChangeDomainPasswordRequestBody(string username, string oldPass, string newPass, string domain) {
            this.username = username;
            this.oldPass = oldPass;
            this.newPass = newPass;
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeDomainPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeDomainPasswordResponse", Namespace="http://mgt-svr/loginService/", Order=0)]
        public PMWelfare.LoginService.ChangeDomainPasswordResponseBody Body;
        
        public ChangeDomainPasswordResponse() {
        }
        
        public ChangeDomainPasswordResponse(PMWelfare.LoginService.ChangeDomainPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mgt-svr/loginService/")]
    public partial class ChangeDomainPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChangeDomainPasswordResult;
        
        public ChangeDomainPasswordResponseBody() {
        }
        
        public ChangeDomainPasswordResponseBody(string ChangeDomainPasswordResult) {
            this.ChangeDomainPasswordResult = ChangeDomainPasswordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UraLoginServiceSoapChannel : PMWelfare.LoginService.UraLoginServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UraLoginServiceSoapClient : System.ServiceModel.ClientBase<PMWelfare.LoginService.UraLoginServiceSoap>, PMWelfare.LoginService.UraLoginServiceSoap {
        
        public UraLoginServiceSoapClient() {
        }
        
        public UraLoginServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UraLoginServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UraLoginServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UraLoginServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PMWelfare.LoginService.GetUserResponse PMWelfare.LoginService.UraLoginServiceSoap.GetUser(PMWelfare.LoginService.GetUserRequest request) {
            return base.Channel.GetUser(request);
        }
        
        public PMWelfare.LoginService.AdEntry GetUser(string accountName, string whoIsSearching, string herPassword, string domain) {
            PMWelfare.LoginService.GetUserRequest inValue = new PMWelfare.LoginService.GetUserRequest();
            inValue.Body = new PMWelfare.LoginService.GetUserRequestBody();
            inValue.Body.accountName = accountName;
            inValue.Body.whoIsSearching = whoIsSearching;
            inValue.Body.herPassword = herPassword;
            inValue.Body.domain = domain;
            PMWelfare.LoginService.GetUserResponse retVal = ((PMWelfare.LoginService.UraLoginServiceSoap)(this)).GetUser(inValue);
            return retVal.Body.GetUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PMWelfare.LoginService.GetUserResponse> PMWelfare.LoginService.UraLoginServiceSoap.GetUserAsync(PMWelfare.LoginService.GetUserRequest request) {
            return base.Channel.GetUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<PMWelfare.LoginService.GetUserResponse> GetUserAsync(string accountName, string whoIsSearching, string herPassword, string domain) {
            PMWelfare.LoginService.GetUserRequest inValue = new PMWelfare.LoginService.GetUserRequest();
            inValue.Body = new PMWelfare.LoginService.GetUserRequestBody();
            inValue.Body.accountName = accountName;
            inValue.Body.whoIsSearching = whoIsSearching;
            inValue.Body.herPassword = herPassword;
            inValue.Body.domain = domain;
            return ((PMWelfare.LoginService.UraLoginServiceSoap)(this)).GetUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PMWelfare.LoginService.AuthenticateUserResponse PMWelfare.LoginService.UraLoginServiceSoap.AuthenticateUser(PMWelfare.LoginService.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public string AuthenticateUser(string username, string pwd) {
            PMWelfare.LoginService.AuthenticateUserRequest inValue = new PMWelfare.LoginService.AuthenticateUserRequest();
            inValue.Body = new PMWelfare.LoginService.AuthenticateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.pwd = pwd;
            PMWelfare.LoginService.AuthenticateUserResponse retVal = ((PMWelfare.LoginService.UraLoginServiceSoap)(this)).AuthenticateUser(inValue);
            return retVal.Body.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PMWelfare.LoginService.AuthenticateUserResponse> PMWelfare.LoginService.UraLoginServiceSoap.AuthenticateUserAsync(PMWelfare.LoginService.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<PMWelfare.LoginService.AuthenticateUserResponse> AuthenticateUserAsync(string username, string pwd) {
            PMWelfare.LoginService.AuthenticateUserRequest inValue = new PMWelfare.LoginService.AuthenticateUserRequest();
            inValue.Body = new PMWelfare.LoginService.AuthenticateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.pwd = pwd;
            return ((PMWelfare.LoginService.UraLoginServiceSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PMWelfare.LoginService.AuthenticateDomainUserResponse PMWelfare.LoginService.UraLoginServiceSoap.AuthenticateDomainUser(PMWelfare.LoginService.AuthenticateDomainUserRequest request) {
            return base.Channel.AuthenticateDomainUser(request);
        }
        
        public string AuthenticateDomainUser(string username, string pwd, string domain) {
            PMWelfare.LoginService.AuthenticateDomainUserRequest inValue = new PMWelfare.LoginService.AuthenticateDomainUserRequest();
            inValue.Body = new PMWelfare.LoginService.AuthenticateDomainUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.pwd = pwd;
            inValue.Body.domain = domain;
            PMWelfare.LoginService.AuthenticateDomainUserResponse retVal = ((PMWelfare.LoginService.UraLoginServiceSoap)(this)).AuthenticateDomainUser(inValue);
            return retVal.Body.AuthenticateDomainUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PMWelfare.LoginService.AuthenticateDomainUserResponse> PMWelfare.LoginService.UraLoginServiceSoap.AuthenticateDomainUserAsync(PMWelfare.LoginService.AuthenticateDomainUserRequest request) {
            return base.Channel.AuthenticateDomainUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<PMWelfare.LoginService.AuthenticateDomainUserResponse> AuthenticateDomainUserAsync(string username, string pwd, string domain) {
            PMWelfare.LoginService.AuthenticateDomainUserRequest inValue = new PMWelfare.LoginService.AuthenticateDomainUserRequest();
            inValue.Body = new PMWelfare.LoginService.AuthenticateDomainUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.pwd = pwd;
            inValue.Body.domain = domain;
            return ((PMWelfare.LoginService.UraLoginServiceSoap)(this)).AuthenticateDomainUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PMWelfare.LoginService.ChangeDomainPasswordResponse PMWelfare.LoginService.UraLoginServiceSoap.ChangeDomainPassword(PMWelfare.LoginService.ChangeDomainPasswordRequest request) {
            return base.Channel.ChangeDomainPassword(request);
        }
        
        public string ChangeDomainPassword(string username, string oldPass, string newPass, string domain) {
            PMWelfare.LoginService.ChangeDomainPasswordRequest inValue = new PMWelfare.LoginService.ChangeDomainPasswordRequest();
            inValue.Body = new PMWelfare.LoginService.ChangeDomainPasswordRequestBody();
            inValue.Body.username = username;
            inValue.Body.oldPass = oldPass;
            inValue.Body.newPass = newPass;
            inValue.Body.domain = domain;
            PMWelfare.LoginService.ChangeDomainPasswordResponse retVal = ((PMWelfare.LoginService.UraLoginServiceSoap)(this)).ChangeDomainPassword(inValue);
            return retVal.Body.ChangeDomainPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PMWelfare.LoginService.ChangeDomainPasswordResponse> PMWelfare.LoginService.UraLoginServiceSoap.ChangeDomainPasswordAsync(PMWelfare.LoginService.ChangeDomainPasswordRequest request) {
            return base.Channel.ChangeDomainPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<PMWelfare.LoginService.ChangeDomainPasswordResponse> ChangeDomainPasswordAsync(string username, string oldPass, string newPass, string domain) {
            PMWelfare.LoginService.ChangeDomainPasswordRequest inValue = new PMWelfare.LoginService.ChangeDomainPasswordRequest();
            inValue.Body = new PMWelfare.LoginService.ChangeDomainPasswordRequestBody();
            inValue.Body.username = username;
            inValue.Body.oldPass = oldPass;
            inValue.Body.newPass = newPass;
            inValue.Body.domain = domain;
            return ((PMWelfare.LoginService.UraLoginServiceSoap)(this)).ChangeDomainPasswordAsync(inValue);
        }
    }
}
